server:
      port: 9901
      
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    empleado:
      path: /empleado/**
      service-id: empleado-ms
    empresa:
      path: /empresa/**
      service-id: empresa-ms
   
                  
eureka:
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}      