---
spring:
  profiles: primary
eureka:
  client:
    service-url:
      defaultZone: http://eureka-secondary:8802/eureka/
server:
  port: 8801
---
spring:
  profiles: secondary
eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8001/eureka/
server:
  port: 8802
